### ISSUE TITLE
[FEAT, INITIAL] Plugin configuration in the repository

### ISSUE THREAD

**Issue by rustatian** [roadrunner-server/velox#2]
The repository should contain a `config.yaml` configuration with the plugin name, import name, alias (if needed).
RR will analyze the repository and attach the plugin automatically to the build.

**Comment by rustatian** [comment]
```toml
[std]
# You don't need to specify a repo for the std plugins
http = "latest"
grpc = "latest"

[custom]
bar = { version = "latest", repo = "github.com/roadrunner-server/static" }
foo = { version = "v1.0.2", repo = "github.com/bar/foo" }
```
